# Generated by Django 4.2.7 on 2023-12-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verificator',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='код верификации почты'),
        ),
    ]
