# Generated by Django 4.2.7 on 2023-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact_alter_product_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название версии'),
        ),
    ]
